import { calculatePriorityScore, getPriorityFromScore } from "./priority";
import type {
  Feedback,
  Insight,
  PainPoint,
  PrdDraft,
  Project,
  Requirement,
} from "./types";

export const demoProject: Project = {
  id: "nova-v32",
  name: "NovaNote V3.2 用户反馈",
  productName: "NovaNote",
  productType: "效率工具 SaaS",
  analysisGoal: "了解版本发布后的用户阻碍，并确定下一次迭代重点",
  dataSource: "应用商店 + 用户调研",
  language: "中文",
  feedbackCount: 1248,
  insightCount: 26,
  status: "analyzed",
  updatedAt: "2 分钟前",
};
export const projects: Project[] = [
  demoProject,
  {
    ...demoProject,
    id: "mobile-v4",
    name: "移动端 V4 内测反馈",
    feedbackCount: 864,
    insightCount: 18,
    status: "processing",
    updatedAt: "18 分钟前",
  },
  {
    ...demoProject,
    id: "q3-survey",
    name: "第三季度用户调研",
    feedbackCount: 526,
    insightCount: 0,
    status: "draft",
    updatedAt: "昨天",
  },
  {
    ...demoProject,
    id: "august-cs",
    name: "八月客户反馈",
    feedbackCount: 312,
    insightCount: 0,
    status: "failed",
    updatedAt: "8 月 12 日",
  },
];
export const feedback: Feedback[] = [
  {
    id: "FB_021",
    content: "Search can't find pages I saved last month.",
    category: "UX",
    intent: "complaint",
    sentiment: "negative",
    sentimentScore: -0.91,
    feature: "Search",
    severity: "high",
    summary: "无法找回已保存的历史页面",
    painPointId: "search-experience",
    confidence: 94,
    source: "App Store",
    rating: 2,
    date: "2026-08-12",
  },
  {
    id: "FB_067",
    content: "Search has become slower and I wait too long for old notes.",
    category: "Performance",
    intent: "complaint",
    sentiment: "negative",
    sentimentScore: -0.84,
    feature: "Search",
    severity: "high",
    summary: "历史内容搜索速度较慢",
    painPointId: "search-experience",
    confidence: 91,
    source: "Survey",
    rating: 2,
    date: "2026-08-11",
  },
  {
    id: "FB_142",
    content:
      "I need filters by date and content type because results are overwhelming.",
    category: "UX",
    intent: "request",
    sentiment: "neutral",
    sentimentScore: -0.18,
    feature: "Search",
    severity: "medium",
    summary: "用户需要筛选条件来缩小结果范围",
    painPointId: "search-experience",
    confidence: 88,
    source: "Community",
    rating: 3,
    date: "2026-08-10",
  },
  {
    id: "FB_203",
    content: "NovaNote crashes whenever I open a large notebook after V3.2.",
    category: "Reliability",
    intent: "report",
    sentiment: "negative",
    sentimentScore: -0.96,
    feature: "App stability",
    severity: "critical",
    summary: "V3.2 更新后打开大型笔记本会崩溃",
    painPointId: "app-stability",
    confidence: 97,
    source: "App Store",
    rating: 1,
    date: "2026-08-09",
  },
  {
    id: "FB_287",
    content: "The paid plan limits are difficult to understand.",
    category: "Pricing",
    intent: "complaint",
    sentiment: "negative",
    sentimentScore: -0.72,
    feature: "Plans",
    severity: "medium",
    summary: "付费套餐限制说明不清晰",
    painPointId: "pricing",
    confidence: 82,
    source: "Customer Service",
    rating: 3,
    date: "2026-08-08",
  },
  {
    id: "FB_354",
    content: "Please let me export multiple notebooks in one operation.",
    category: "Feature",
    intent: "request",
    sentiment: "neutral",
    sentimentScore: 0.05,
    feature: "Export",
    severity: "medium",
    summary: "用户希望支持批量导出",
    painPointId: "data-export",
    confidence: 93,
    source: "Survey",
    rating: 4,
    date: "2026-08-07",
  },
  {
    id: "FB_401",
    content: "Login codes often arrive too late and expire.",
    category: "Reliability",
    intent: "complaint",
    sentiment: "negative",
    sentimentScore: -0.76,
    feature: "Login",
    severity: "medium",
    summary: "登录验证码到达延迟",
    painPointId: "login",
    confidence: 86,
    source: "Customer Service",
    rating: 2,
    date: "2026-08-06",
  },
];
export const painPoints: PainPoint[] = [
  {
    id: "search-experience",
    slug: "search-experience",
    name: "搜索体验",
    description: "用户经常无法快速找回之前创建或保存的内容。",
    feedbackCount: 186,
    percentage: 18.7,
    severity: "high",
    confidence: 94,
    negativeRate: 82,
    subtopics: [
      { name: "搜索召回", percentage: 43 },
      { name: "历史内容", percentage: 31 },
      { name: "搜索速度", percentage: 17 },
      { name: "筛选能力", percentage: 9 },
    ],
    supportingFeedbackIds: ["FB_021", "FB_067", "FB_142"],
    userNeed: "用户需要快速、可靠地定位之前创建或保存的信息。",
    opportunity: "通过优化索引、排序和高级筛选提升信息检索体验。",
  },
  {
    id: "app-stability",
    slug: "app-stability",
    name: "应用稳定性",
    description: "崩溃与卡顿会中断用户的核心工作流程。",
    feedbackCount: 142,
    percentage: 14.2,
    severity: "critical",
    confidence: 96,
    negativeRate: 91,
    subtopics: [
      { name: "崩溃", percentage: 54 },
      { name: "卡顿", percentage: 28 },
      { name: "启动", percentage: 18 },
    ],
    supportingFeedbackIds: ["FB_203"],
    userNeed: "用户需要稳定可靠地访问自己的笔记。",
    opportunity: "降低启动和大型笔记本场景中的崩溃率。",
  },
  {
    id: "pricing",
    slug: "pricing",
    name: "价格与套餐",
    description: "用户难以理解不同套餐的功能限制。",
    feedbackCount: 97,
    percentage: 11.8,
    severity: "medium",
    confidence: 82,
    negativeRate: 68,
    subtopics: [
      { name: "套餐限制", percentage: 62 },
      { name: "价值感知", percentage: 38 },
    ],
    supportingFeedbackIds: ["FB_287"],
    userNeed: "用户需要清晰了解各套餐的权益边界。",
    opportunity: "在套餐比较和升级环节清楚说明功能限制。",
  },
  {
    id: "data-export",
    slug: "data-export",
    name: "数据导出",
    description: "用户需要高效地批量导出数据。",
    feedbackCount: 83,
    percentage: 9.3,
    severity: "medium",
    confidence: 90,
    negativeRate: 61,
    subtopics: [
      { name: "批量导出", percentage: 72 },
      { name: "导出格式", percentage: 28 },
    ],
    supportingFeedbackIds: ["FB_354"],
    userNeed: "用户希望减少重复操作，并便捷地迁移自己的数据。",
    opportunity: "提供稳定可靠的批量导出能力。",
  },
  {
    id: "login",
    slug: "login",
    name: "登录体验",
    description: "验证码延迟会阻碍用户正常登录。",
    feedbackCount: 76,
    percentage: 7.1,
    severity: "medium",
    confidence: 86,
    negativeRate: 74,
    subtopics: [
      { name: "验证码", percentage: 70 },
      { name: "第三方登录", percentage: 30 },
    ],
    supportingFeedbackIds: ["FB_401"],
    userNeed: "用户需要稳定、便捷地进入自己的账户。",
    opportunity: "提升验证码可靠性，并增加便捷的登录方式。",
  },
];
const req = (
  base: Omit<
    Requirement,
    "priorityScore" | "priority" | "aiPriority" | "manualPriority"
  >,
): Requirement => {
  const priorityScore = calculatePriorityScore({
    frequency: base.frequencyScore,
    severity: base.severityScore,
    impact: base.impactScore,
    businessValue: base.businessValue,
    confidence: base.confidenceScore,
  });
  const priority = getPriorityFromScore(priorityScore);
  return {
    ...base,
    priorityScore,
    priority,
    aiPriority: priority,
    manualPriority: null,
  };
};
export const requirements: Requirement[] = [
  req({
    id: "search-optimization",
    painPointId: "search-experience",
    title: "搜索体验优化",
    userNeed: painPoints[0].userNeed,
    frequencyScore: 95,
    severityScore: 90,
    impactScore: 95,
    businessValue: 80,
    confidenceScore: 92,
    feedbackCount: 186,
  }),
  req({
    id: "stability-improvement",
    painPointId: "app-stability",
    title: "应用稳定性提升",
    userNeed: painPoints[1].userNeed,
    frequencyScore: 82,
    severityScore: 100,
    impactScore: 95,
    businessValue: 75,
    confidenceScore: 94,
    feedbackCount: 142,
  }),
  req({
    id: "batch-export",
    painPointId: "data-export",
    title: "批量导出",
    userNeed: painPoints[3].userNeed,
    frequencyScore: 55,
    severityScore: 50,
    impactScore: 65,
    businessValue: 70,
    confidenceScore: 88,
    feedbackCount: 83,
  }),
  req({
    id: "wechat-login",
    painPointId: "login",
    title: "微信登录",
    userNeed: painPoints[4].userNeed,
    frequencyScore: 48,
    severityScore: 50,
    impactScore: 60,
    businessValue: 65,
    confidenceScore: 78,
    feedbackCount: 76,
  }),
  req({
    id: "dark-mode",
    painPointId: "pricing",
    title: "深色模式",
    userNeed: "用户需要在弱光环境下舒适地阅读和编辑内容。",
    frequencyScore: 35,
    severityScore: 20,
    impactScore: 50,
    businessValue: 45,
    confidenceScore: 72,
    feedbackCount: 59,
  }),
];
export const insights: Insight[] = [
  {
    id: "INS_001",
    title: "搜索相关投诉增长 23%",
    detail: "历史内容检索是当前最主要的搜索问题。",
    painPointId: "search-experience",
    evidenceCount: 186,
    confidence: 94,
  },
  {
    id: "INS_002",
    title: "崩溃问题集中出现在 V3.2 更新后",
    detail: "大型笔记本是稳定性问题最明显的使用场景。",
    painPointId: "app-stability",
    evidenceCount: 142,
    confidence: 96,
  },
  {
    id: "INS_003",
    title: "批量导出需求持续上升",
    detail: "团队用户反馈逐个导出带来大量重复操作。",
    painPointId: "data-export",
    evidenceCount: 83,
    confidence: 90,
  },
];
export const sentimentData = {
  "7 days": [
    { d: "周一", p: 34, n: 42, u: 24 },
    { d: "周二", p: 31, n: 45, u: 24 },
    { d: "周三", p: 37, n: 41, u: 22 },
    { d: "周四", p: 39, n: 40, u: 21 },
    { d: "周五", p: 41, n: 38, u: 21 },
    { d: "周六", p: 44, n: 36, u: 20 },
    { d: "周日", p: 42, n: 37, u: 21 },
  ],
  "30 days": [
    { d: "第 1 周", p: 39, n: 38, u: 23 },
    { d: "第 2 周", p: 36, n: 42, u: 22 },
    { d: "第 3 周", p: 34, n: 45, u: 21 },
    { d: "第 4 周", p: 42, n: 37, u: 21 },
  ],
  "90 days": [
    { d: "6 月", p: 45, n: 32, u: 23 },
    { d: "7 月", p: 41, n: 36, u: 23 },
    { d: "8 月", p: 36, n: 42, u: 22 },
  ],
};
export const prdDraft: PrdDraft = {
  id: "PRD_001",
  requirementId: "search-optimization",
  title: "搜索体验优化 PRD",
  hasHumanEdits: false,
  sections: {
    background: "NovaNote V3.2 中共有 186 条反馈与搜索体验相关。",
    problemStatement: "用户无法稳定地找回历史内容或已保存的信息。",
    userEvidence: "FB_021、FB_067 和 FB_142 分别反映了召回、速度与筛选问题。",
    userNeed: painPoints[0].userNeed,
    productGoal: "让历史内容检索变得快速、准确且结果可解释。",
    successMetrics: "提升历史内容搜索成功率，降低无结果搜索占比。",
    userStories:
      "作为 NovaNote 用户，我希望快速找到已保存的内容，以便继续之前的工作。",
    functionalRequirements: "优化索引；调整排序；增加日期和内容类型筛选。",
    edgeCases: "超大型工作区；已删除内容；离线索引；多语言查询。",
    analytics: "跟踪查询延迟、无结果率、筛选使用率和结果点击率。",
    acceptanceCriteria:
      "输入准确关键词时可找到历史笔记，使用筛选条件后结果会正确更新。",
  },
};
