import { calculatePriorityScore, getPriorityFromScore } from "./priority";
import type { Feedback, Insight, PainPoint, PrdDraft, Project, Requirement } from "./types";

export const demoProject: Project={id:"nova-v32",name:"NovaNote V3.2 User Feedback",productName:"NovaNote",productType:"Productivity SaaS",analysisGoal:"Understand post-release friction and prioritize the next iteration",dataSource:"App Store + Survey",language:"English",feedbackCount:1248,insightCount:26,status:"analyzed",updatedAt:"2m ago"};
export const projects:Project[]=[demoProject,{...demoProject,id:"mobile-v4",name:"Mobile V4 Beta",feedbackCount:864,insightCount:18,status:"processing",updatedAt:"18m ago"},{...demoProject,id:"q3-survey",name:"Q3 User Survey",feedbackCount:526,insightCount:0,status:"draft",updatedAt:"Yesterday"},{...demoProject,id:"august-cs",name:"Customer Feedback August",feedbackCount:312,insightCount:0,status:"failed",updatedAt:"Aug 12"}];
export const feedback:Feedback[]=[
{id:"FB_021",content:"Search can't find pages I saved last month.",category:"UX",intent:"complaint",sentiment:"negative",sentimentScore:-.91,feature:"Search",severity:"high",summary:"Saved historical pages cannot be retrieved",painPointId:"search-experience",confidence:94,source:"App Store",rating:2,date:"2026-08-12"},
{id:"FB_067",content:"Search has become slower and I wait too long for old notes.",category:"Performance",intent:"complaint",sentiment:"negative",sentimentScore:-.84,feature:"Search",severity:"high",summary:"Historical search is slow",painPointId:"search-experience",confidence:91,source:"Survey",rating:2,date:"2026-08-11"},
{id:"FB_142",content:"I need filters by date and content type because results are overwhelming.",category:"UX",intent:"request",sentiment:"neutral",sentimentScore:-.18,feature:"Search",severity:"medium",summary:"Users need filters to narrow results",painPointId:"search-experience",confidence:88,source:"Community",rating:3,date:"2026-08-10"},
{id:"FB_203",content:"NovaNote crashes whenever I open a large notebook after V3.2.",category:"Reliability",intent:"report",sentiment:"negative",sentimentScore:-.96,feature:"App stability",severity:"critical",summary:"Large notebooks crash after V3.2",painPointId:"app-stability",confidence:97,source:"App Store",rating:1,date:"2026-08-09"},
{id:"FB_287",content:"The paid plan limits are difficult to understand.",category:"Pricing",intent:"complaint",sentiment:"negative",sentimentScore:-.72,feature:"Plans",severity:"medium",summary:"Plan limits lack clarity",painPointId:"pricing",confidence:82,source:"Customer Service",rating:3,date:"2026-08-08"},
{id:"FB_354",content:"Please let me export multiple notebooks in one operation.",category:"Feature",intent:"request",sentiment:"neutral",sentimentScore:.05,feature:"Export",severity:"medium",summary:"Users want batch export",painPointId:"data-export",confidence:93,source:"Survey",rating:4,date:"2026-08-07"},
{id:"FB_401",content:"Login codes often arrive too late and expire.",category:"Reliability",intent:"complaint",sentiment:"negative",sentimentScore:-.76,feature:"Login",severity:"medium",summary:"Login verification codes are delayed",painPointId:"login",confidence:86,source:"Customer Service",rating:2,date:"2026-08-06"}];
export const painPoints:PainPoint[]=[
{id:"search-experience",slug:"search-experience",name:"Search Experience",description:"Users frequently struggle to retrieve previously created or saved content.",feedbackCount:186,percentage:18.7,severity:"high",confidence:94,negativeRate:82,subtopics:[{name:"Search Recall",percentage:43},{name:"Historical Content",percentage:31},{name:"Search Speed",percentage:17},{name:"Filtering",percentage:9}],supportingFeedbackIds:["FB_021","FB_067","FB_142"],userNeed:"Users need a fast and reliable way to locate previously created or saved information.",opportunity:"Improve information retrieval through better indexing, ranking and advanced search filters."},
{id:"app-stability",slug:"app-stability",name:"App Stability",description:"Crashes and freezes interrupt core workflows.",feedbackCount:142,percentage:14.2,severity:"critical",confidence:96,negativeRate:91,subtopics:[{name:"Crash",percentage:54},{name:"Freeze",percentage:28},{name:"Startup",percentage:18}],supportingFeedbackIds:["FB_203"],userNeed:"Users need reliable access to their notes.",opportunity:"Reduce crashes across startup and large notebook workflows."},
{id:"pricing",slug:"pricing",name:"Pricing",description:"Plan limits are difficult to understand.",feedbackCount:97,percentage:11.8,severity:"medium",confidence:82,negativeRate:68,subtopics:[{name:"Plan limits",percentage:62},{name:"Value",percentage:38}],supportingFeedbackIds:["FB_287"],userNeed:"Users need clear plan boundaries.",opportunity:"Clarify limits at comparison and upgrade moments."},
{id:"data-export",slug:"data-export",name:"Data Export",description:"Users need efficient bulk export.",feedbackCount:83,percentage:9.3,severity:"medium",confidence:90,negativeRate:61,subtopics:[{name:"Batch export",percentage:72},{name:"Formats",percentage:28}],supportingFeedbackIds:["FB_354"],userNeed:"Users need portable data with less repetitive work.",opportunity:"Support reliable batch export."},
{id:"login",slug:"login",name:"Login",description:"Delayed verification blocks access.",feedbackCount:76,percentage:7.1,severity:"medium",confidence:86,negativeRate:74,subtopics:[{name:"Verification",percentage:70},{name:"Social login",percentage:30}],supportingFeedbackIds:["FB_401"],userNeed:"Users need dependable access.",opportunity:"Improve verification reliability and login options."}];
const req=(base:Omit<Requirement,"priorityScore"|"priority"|"aiPriority"|"manualPriority">):Requirement=>{const priorityScore=calculatePriorityScore({frequency:base.frequencyScore,severity:base.severityScore,impact:base.impactScore,businessValue:base.businessValue,confidence:base.confidenceScore});const priority=getPriorityFromScore(priorityScore);return{...base,priorityScore,priority,aiPriority:priority,manualPriority:null}};
export const requirements:Requirement[]=[req({id:"search-optimization",painPointId:"search-experience",title:"Search Optimization",userNeed:painPoints[0].userNeed,frequencyScore:95,severityScore:90,impactScore:95,businessValue:80,confidenceScore:92,feedbackCount:186}),req({id:"stability-improvement",painPointId:"app-stability",title:"App Stability Improvement",userNeed:painPoints[1].userNeed,frequencyScore:82,severityScore:100,impactScore:95,businessValue:75,confidenceScore:94,feedbackCount:142}),req({id:"batch-export",painPointId:"data-export",title:"Batch Export",userNeed:painPoints[3].userNeed,frequencyScore:55,severityScore:50,impactScore:65,businessValue:70,confidenceScore:88,feedbackCount:83}),req({id:"wechat-login",painPointId:"login",title:"WeChat Login",userNeed:painPoints[4].userNeed,frequencyScore:48,severityScore:50,impactScore:60,businessValue:65,confidenceScore:78,feedbackCount:76}),req({id:"dark-mode",painPointId:"pricing",title:"Dark Mode",userNeed:"Users need comfortable reading in low-light environments.",frequencyScore:35,severityScore:20,impactScore:50,businessValue:45,confidenceScore:72,feedbackCount:59})];
export const insights:Insight[]=[{id:"INS_001",title:"Search complaints increased by 23%",detail:"Historical retrieval is the dominant search issue.",painPointId:"search-experience",evidenceCount:186,confidence:94},{id:"INS_002",title:"Crashes concentrate after V3.2",detail:"Large notebooks are the strongest stability signal.",painPointId:"app-stability",evidenceCount:142,confidence:96},{id:"INS_003",title:"Batch export demand is rising",detail:"Teams report repetitive one-by-one exports.",painPointId:"data-export",evidenceCount:83,confidence:90}];
export const sentimentData={"7 days":[{d:"M",p:34,n:42,u:24},{d:"T",p:31,n:45,u:24},{d:"W",p:37,n:41,u:22},{d:"T",p:39,n:40,u:21},{d:"F",p:41,n:38,u:21},{d:"S",p:44,n:36,u:20},{d:"S",p:42,n:37,u:21}],"30 days":[{d:"W1",p:39,n:38,u:23},{d:"W2",p:36,n:42,u:22},{d:"W3",p:34,n:45,u:21},{d:"W4",p:42,n:37,u:21}],"90 days":[{d:"Jun",p:45,n:32,u:23},{d:"Jul",p:41,n:36,u:23},{d:"Aug",p:36,n:42,u:22}]};
export const prdDraft:PrdDraft={id:"PRD_001",requirementId:"search-optimization",title:"Search Optimization PRD",hasHumanEdits:false,sections:{background:"NovaNote V3.2 generated 186 feedback items related to search experience.",problemStatement:"Users cannot reliably retrieve historical or saved content.",userEvidence:"FB_021, FB_067 and FB_142 demonstrate recall, speed and filtering issues.",userNeed:painPoints[0].userNeed,productGoal:"Make historical content retrieval fast, accurate and explainable.",successMetrics:"Increase successful historical searches; reduce zero-result searches.",userStories:"As a NovaNote user, I want to find saved content quickly so I can continue my work.",functionalRequirements:"Improve indexing; tune ranking; add date and content-type filters.",edgeCases:"Very large workspaces; deleted content; offline indexes; multilingual queries.",analytics:"Track query latency, zero-result rate, filter use and result clicks.",acceptanceCriteria:"Historical notes appear for exact keywords and supported filters update results."}};
